# Generated by Django 2.2.5 on 2019-09-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image', models.TextField(blank=True)),
                ('largeImage', models.TextField(blank=True)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
